# Generated by Django 3.1.7 on 2021-04-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('courseBackground', models.CharField(max_length=255)),
                ('courseTarget', models.CharField(max_length=255)),
                ('courseFramework', models.CharField(max_length=255)),
                ('openState', models.BooleanField(default=True)),
                ('approvalState', models.IntegerField(default=0)),
            ],
        ),
    ]
